### ISSUE TITLE
Message not showing up in QQ group

### ISSUE THREAD

**Issue by portwatcher** [Drincann/Mirai-js#136]
```javascript
  await bot.sendMessage({
    group: data.sender.group.id,
    message: new Message().addAt(data.sender.id).addText(` ${result}`),
  })
  console.log(`${data.sender.id}: reply to ${data.sender.id} in ${data.sender.group.id}`)
```

Here is how mcl shows output
![image](https://user-images.githubusercontent.com/2919533/148553430-7822a466-e5b0-4788-a746-a13d29e15f0f.png)

Here is the log of my code
![image](https://user-images.githubusercontent.com/2919533/148553540-557ada4b-f5b6-4b97-914e-c5226f0247a1.png)

However, the message doesn't show up.

Friend chat works perfectly.

**Comment by portwatcher** [comment]
https://github.com/mamoe/mirai/issues/1209

**Comment by portwatcher** [comment]
mamoe/mirai#1209

**Comment by Drincann** [comment]
这个跟腾讯有关，算是玄学问题，一般过一段时间就好了。

**Comment by portwatcher** [comment]
好的
