### ISSUE TITLE
How to reply temp message coming from qq group

### ISSUE THREAD

**Issue by portwatcher** [Drincann/Mirai-js#137]
I've tried
```
await bot.sendMessage({
  temp: true,
  friend: data.sender.id,
  group: data.sender.group.id,
  message: new Message().addAt(data.sender.id).addText(` ${result}`),
})
console.log(`${new Date().toLocaleString()} ${data.sender.id}: reply to ${data.sender.id} from ${data.sender.group.id} temp message`)
```

But senders received no replies.
I've checked
https://github.com/project-mirai/mirai-api-http/blob/master/docs/api/API.md#%E5%8F%91%E9%80%81%E4%B8%B4%E6%97%B6%E4%BC%9A%E8%AF%9D%E6%B6%88%E6%81%AF
and https://github.com/Drincann/Mirai-js/blob/3ba8e6d57a9cff055c39082ac6f0dcda7f687d62/dist/node/Bot.js#L364

It seems this is the same issue with https://github.com/Drincann/Mirai-js/issues/136 , caused by Tencent security policy.

**Comment by Drincann** [comment]
我测试了可以正常发送临时消息，应该是腾讯的问题。
