### ISSUE TITLE
开发文档首页Get Started链接404与奇怪的自动下滑

### ISSUE THREAD

**Issue by lincannm** [Drincann/Mirai-js#143]
在[开发文档](https://mirai-js-drincann.vercel.app/)首页里面点击Get Started按钮会跳转到<https://mirai-js-drincann.vercel.app/#/Preparation>并显示404 Not found。然而正确的链接是<https://mirai-js-drincann.vercel.app/#/v2.x/Preparation>。这样的情况在手机端上浏览开发文档不太方便。

还有进入链接后会下滑到网页的Mirai-js文字位置，感觉怪怪的：
![Screenshot_2022-02-19-22-36-30-590_mark via](https://user-images.githubusercontent.com/41236336/154805449-00752731-a25a-4fbe-9ff4-873ad8dab4a7.jpg)
建议移除这个行为或者直接下滑到下面的正文部分。

**Comment by Drincann** [comment]
其实我感觉下滑的行为还挺有感觉的。&#x1F436;

**Comment by lincannm** [comment]
> 其实我感觉下滑的行为还挺有感觉的。🐶

感觉有点烦，还不如我自己一滑就滑到底了😂

**Comment by lincannm** [comment]
> > 其实我感觉下滑的行为还挺有感觉的。🐶
> 
> 感觉有点烦，还不如我自己一滑就滑到底了😂

毕竟写机器人的时候会时常访问
