### ISSUE TITLE
node运行示例文档中的问题

### ISSUE THREAD

**Issue by Uwwal** [Drincann/Mirai-js#16]
参照文档快速开始中的步骤, 我未安装git, 于是我download zip.
修改demo.js中authkey, qq, password后, 我先.\mcl登录bot, 而后使用cmd执行demo.js, 输出如下.
![image](https://user-images.githubusercontent.com/69232066/107920560-1e642300-6fa8-11eb-8c58-2c5f89aa0fb5.png)

版本:
![image](https://user-images.githubusercontent.com/69232066/107920783-76028e80-6fa8-11eb-95bf-7917f5e79493.png)

顺便快速开始这里的文档过于简略了..

**Comment by Drincann** [comment]
![image](https://user-images.githubusercontent.com/53897259/107921022-d691cb80-6fa8-11eb-972e-12acd03d69ba.png)

我使用了一些 es6 的语法，如上图的 null 判断 `??` 和链判断 `.?`，你的 node 版本应该还未实现。

我不确定是在哪个版本开始支持的，但我本地的 node 版本是 ` v14.15.4`，运行良好。

顺便问一下，关于文档有什么建议吗？缺少哪方面内容呢。
