### ISSUE TITLE
提案征集

### ISSUE THREAD

**Issue by Drincann** [Drincann/Mirai-js#18]
有没有什么好的点子，feature、bug、doc、refactor 等等。

欢迎在下方提出，或参与开发。

**Comment by papadave66** [comment]
可否尝试兼容低版本的nodejs . 我在使用v12.20.1 的nodejs 运行时错误。貌似是一些语法v12 中不支持

**Comment by Drincann** [comment]
> 可否尝试兼容低版本的nodejs . 我在使用v12.20.1 的nodejs 运行时错误。貌似是一些语法v12 中不支持

我用 babel 打包一下吧。

可以考虑暂时通过现代浏览器开发和测试，接口风格都一样的，没有迁移成本。

**Comment by Drincann** [comment]
> 可否尝试兼容低版本的nodejs . 我在使用v12.20.1 的nodejs 运行时错误。貌似是一些语法v12 中不支持

已经发布在 1.6.0
