### ISSUE TITLE
关于 中间件 Middleware 中 memberJoinRequestProcessor 的一些错误

### ISSUE THREAD

**Issue by guation** [Drincann/Mirai-js#19]
在文档中关于加群消息的事件的中间件memberJoinRequestProcessor将MemberJoinRequestEvent写为NewFriendRequestEvent。按照示例的程序片段无法监听到加群请求。
![QQ截图20210226132621](https://user-images.githubusercontent.com/30709641/109259230-c1356080-7836-11eb-9225-08431803979c.png)
并且代码中也存在了相应的问题，修改示例程序使用正确的监听事件后程序将抛出消息格式错误的异常。
![QQ截图20210226132441](https://user-images.githubusercontent.com/30709641/109259669-a6172080-7837-11eb-83e1-5e65795bd209.png)
在invitedJoinGroupRequestProcessor中间件的文档也存在同样的笔误。
![QQ截图20210226132658](https://user-images.githubusercontent.com/30709641/109259681-ab746b00-7837-11eb-8872-40da62d1e67b.png)

**Comment by Drincann** [comment]
我咋说当时咋测试都没用呢，还以为是 mirai-api-http 的问题。。

**Comment by Drincann** [comment]
npm 上的包已经更新到 1.0.1。

更新后还存在问题请 reopen。

**Comment by guation** [comment]
sendMessage 方法的 message 参数不能接受messageChain。
![QQ截图20210226155417](https://user-images.githubusercontent.com/30709641/109272383-c355ea00-784b-11eb-971b-438a7abc8719.png)
```
bot.on('FriendMessage', async data => {
    await bot.sendMessage({
        // 群号
        group: '759568028',
        // 是 http server 接口所需的原始格式，若提供则优先使用
        message: [
            { type: 'Plain', text: 'hello world!' },
        ],
    });
});
```
使用以上代码发送消息时会报错400。
```
PS > node .\app.js
(node:15408) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
参数格式错误
    at module.exports (node_modules\mirai-js\src\util\errorHandler.js:15:15)
    at module.exports (node_modules\mirai-js\src\core\sendGroupMessage.js:31:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Bot.sendMessage (node_modules\mirai-js\src\Bot.js:252:24)
    at async app.js:17:5
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15408) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
将message替换为messageChain则可以正确发送消息，后台输出warning。
`warning: 现在 sendMessage 方法的 message 参数可以同时接收 Message 实例或 messageChain，messageChain 参数将在未来被移除`

**Comment by Drincann** [comment]
npm 上的包已经更新到 1.0.2
