### ISSUE TITLE
不能连接到服务端

### ISSUE THREAD

**Issue by 214116734** [Drincann/Mirai-js#208]
文件太大，不能上传
http://110.42.181.89:8888/down/47H5isiNMvpF

**Comment by Drincann** [comment]
这个资源无法访问，麻烦检查一下。

![image](https://user-images.githubusercontent.com/53897259/172611417-673afab8-10d3-4a07-833d-b30653c339b6.png)

**Comment by Drincann** [comment]
如有需要，可以 reopen
