### ISSUE TITLE
pr #211 npm未同步更新，问题仍未解决

### ISSUE THREAD

**Issue by FurryR** [Drincann/Mirai-js#212]

**Comment by Drincann** [comment]
#211 没有带 dist，请问是 husky 的 git hooks 出了问题吗？

**Comment by FurryR** [comment]
> #211 没有带 dist，请问是 husky 的 git hooks 出了问题吗？

随后的 commit 立刻在 `dist` 同步了内容，但 `npm update` 和 `npm remove + npm install` 获得到的内容仍然是有问题的。

**Comment by Drincann** [comment]
5ba5e88
