### ISSUE TITLE
Bot.groupPermission's behavior is not as expected

### ISSUE THREAD

**Issue by Mantou1233** [Drincann/Mirai-js#213]
in Bot class, all properies of groupPermission returns GroupPermission
![image](https://user-images.githubusercontent.com/74487898/181760931-c678ca47-067c-4a0a-8bf2-1302698a3ecf.png)
i think this should be fixed? since, you cant get member from admin, etc

**Comment by Drincann** [comment]
This problem may cause semantic conflicts in the typescript.
Maybe you can solve it?

**Comment by Mantou1233** [comment]
done
