### ISSUE TITLE
mirai-api-http v2.6.0 不兼容变更

### ISSUE THREAD

**Issue by Drincann** [Drincann/Mirai-js#220]
https://github.com/project-mirai/mirai-api-http/releases/tag/v2.6.0

涉及一些带有 messageId 参数的接口

- [x] 撤回
- [x] 设置群精华消息
- [x] 获取指定消息

**Comment by Drincann** [comment]
需要做好对低版本的兼容性。

**Comment by Drincann** [comment]
- 获取指定消息 7d8c55a

**Comment by a77uu** [comment]
关于[撤回接口](https://github.com/project-mirai/mirai-api-http/blob/master/docs/api/API.md#%E6%92%A4%E5%9B%9E%E6%B6%88%E6%81%AF)：mirai-api-http 中需要 sessionKey, messageId, target 参数。目前 recall 仅有 messageId 参数，导致调用时会提示 “无效参数”

**Comment by Drincann** [comment]
> 关于[撤回接口](https://github.com/project-mirai/mirai-api-http/blob/master/docs/api/API.md#%E6%92%A4%E5%9B%9E%E6%B6%88%E6%81%AF)：mirai-api-http 中需要 sessionKey, messageId, target 参数。
> 
> 目前 recall 仅有 messageId 参数，导致调用时会提示 “无效参数”

感谢反馈。

fixed 2a4cfcb06833310f21fd19a5b2a782f5c7344bbc v2.8.7
