### ISSUE TITLE
mirai-api-http 2.0 的不兼容

### ISSUE THREAD

**Issue by Riceneeder** [Drincann/Mirai-js#68]
在使用 [mirai-api-http](https://github.com/project-mirai/mirai-api-http) 2.0 时出现404错误
`(node:40099) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404`
代码：
`(async ()=>{
    try{
        var isLoggedIn = await Bot.isBotLoggedIn({
            baseUrl:'http://localhost:8080',
            verifyKey:verfyKey,
            qq:user.No1.ID
        })
        if(isLoggedIn){
            log.info(``QQ:${user.No1.ID} has logged!``);
        }else{
            var {message} = await Bot.sendCommand({
                baseUrl:'http://localhost:8080',
                verifyKey:verfyKey,
                command:'/login',
                args: [user.No1.ID,user.No1.PASSWORD]
            })
            log.info(message);
        }
    }catch(error){
        log.error(error);
    }
})();`

**Comment by Drincann** [comment]
这个接口应该是去掉了，mah 文档没有更新。

未来要从底层用 ts 重写，全面迁移到 ws adaptor，先将就用吧。
